# Site Settings
title: Mariot Tsitoara
url: 'https://mariot.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Mariot Tsitoara
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Python/JavaScript developer and Data Analyst.<br>
Expert in Django and NodeJS/AngularJS. Fluent in NoSQL databases.<br>
I'm looking for a job where I can work with a lot of Data. I like to experiment with Machine Learning and bots'

#sidebar links
email: mariot.tsitoara@gmail.com
phone: +261343916159
website: mariot.github.io #do not add http://
linkedin: mariottsitoara
github: mariot
twitter: 'mariot_tsitoara'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
